-- Populando a tabela de perícias
INSERT INTO pericias (nome, atributo, descricao) VALUES
('Acrobacia', 'DES', 'Você consegue fazer proezas acrobáticas.'),
('Adestramento', 'CAR', 'Você sabe lidar com animais.'),
('Atletismo', 'FOR', 'Você pode realizar façanhas atléticas.'),
('Atuação', 'CAR', 'Você sabe fazer apresentações artísticas, incluindo música, dança e dramaturgia.'),
('Cavalgar', 'DES', 'Você sabe conduzir animais de montaria, como cavalos, trobos e grifos.'),
('Conhecimento', 'INT', 'Você estudou diversos campos do saber, como aritmética, astronomia, dialética, geografia, história...'),
('Cura', 'SAB', 'Você sabe tratar ferimentos, doenças e venenos.'),
('Diplomacia', 'CAR', 'Você convence pessoas com lábia e argumentação.'),
('Enganação', 'CAR', 'Você manipula pessoas com blefes e trapaças.'),
('Fortitude', 'CON', 'Você usa esta perícia para resistir a efeitos que exigem vitalidade, como doenças e venenos.'),
('Furtividade', 'DES', 'Você sabe ser discreto e sorrateiro.'),
('Guerra', 'INT', 'Você foi educado em tática, estratégia e logística.'),
('Iniciativa', 'DES', 'Esta perícia determina sua velocidade de reação em situações de perigo.'),
('Intimidação', 'CAR', 'Você pode assustar ou coagir outras pessoas.'),
('Intuição', 'SAB', 'Esta perícia mede sua empatia e “sexto sentido”.'),
('Investigação', 'INT', 'Você sabe encontrar pistas e informações.'),
('Jogatina', 'CAR', 'Você sabe jogar jogos de azar.'),
('Ladinagem', 'DES', 'Você sabe exercer atividades ilícitas.'),
('Luta', 'FOR', 'Você usa Luta para fazer ataques corpo a corpo.'),
('Misticismo', 'INT', 'Esta perícia envolve o conhecimento de magias, itens mágicos e fenômenos sobrenaturais.'),
('Nobreza', 'INT', 'Você recebeu a educação de um nobre.'),
('Ofício', 'INT', 'Ofício na verdade são várias perícias diferentes. Cada uma permite fabricar itens de certas categorias.'),
('Percepção', 'SAB', 'Você nota coisas usando seus sentidos.'),
('Pilotagem', 'DES', 'Você sabe operar veículos como carroças, barcos e balões.'),
('Pontaria', 'DES', 'Você usa Pontaria para fazer ataques à distância.'),
('Reflexos', 'DES', 'Você usa esta perícia para resistir a efeitos que exigem reação rápida, como armadilhas e explosões.'),
('Religião', 'SAB', 'Você possui conhecimento sobre os deuses e as religiões de Arton.'),
('Sobrevivência', 'SAB', 'Você está em casa nos ermos.'),
('Vontade', 'SAB', 'Você usa esta perícia para resistir a efeitos que exigem determinação, como intimidação e encantamentos.');

-- Atualizando a quantidade de perícias de escolha para cada classe
UPDATE classes SET pericias_quantidade = 2 WHERE nome = 'Arcanista';
UPDATE classes SET pericias_quantidade = 4 WHERE nome = 'Bárbaro';
UPDATE classes SET pericias_quantidade = 6 WHERE nome = 'Bardo';
UPDATE classes SET pericias_quantidade = 4 WHERE nome = 'Bucaneiro';
UPDATE classes SET pericias_quantidade = 4 WHERE nome = 'Caçador';
UPDATE classes SET pericias_quantidade = 2 WHERE nome = 'Cavaleiro';
UPDATE classes SET pericias_quantidade = 2 WHERE nome = 'Clérigo';
UPDATE classes SET pericias_quantidade = 4 WHERE nome = 'Druida';
UPDATE classes SET pericias_quantidade = 2 WHERE nome = 'Guerreiro';
UPDATE classes SET pericias_quantidade = 4 WHERE nome = 'Inventor';
UPDATE classes SET pericias_quantidade = 8 WHERE nome = 'Ladino';
UPDATE classes SET pericias_quantidade = 4 WHERE nome = 'Lutador';
UPDATE classes SET pericias_quantidade = 4 WHERE nome = 'Nobre';
UPDATE classes SET pericias_quantidade = 2 WHERE nome = 'Paladino';

-- Populando a tabela origem_pericias
-- (Supondo que as tabelas 'origens' e 'pericias' já estejam populadas com IDs)
INSERT INTO origem_pericias (origem_id, pericia_id) VALUES
((SELECT id FROM origens WHERE nome = 'Acólito'), (SELECT id FROM pericias WHERE nome = 'Cura')),
((SELECT id FROM origens WHERE nome = 'Acólito'), (SELECT id FROM pericias WHERE nome = 'Religião')),
((SELECT id FROM origens WHERE nome = 'Acólito'), (SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM origens WHERE nome = 'Amigo dos Animais'), (SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM origens WHERE nome = 'Amigo dos Animais'), (SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM origens WHERE nome = 'Aristocrata'), (SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM origens WHERE nome = 'Aristocrata'), (SELECT id FROM pericias WHERE nome = 'Enganação')),
((SELECT id FROM origens WHERE nome = 'Aristocrata'), (SELECT id FROM pericias WHERE nome = 'Nobreza')),
((SELECT id FROM origens WHERE nome = 'Artesão'), (SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM origens WHERE nome = 'Artesão'), (SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM origens WHERE nome = 'Artista'), (SELECT id FROM pericias WHERE nome = 'Atuação')),
((SELECT id FROM origens WHERE nome = 'Artista'), (SELECT id FROM pericias WHERE nome = 'Enganação')),
((SELECT id FROM origens WHERE nome = 'Assistente de Laboratório'), (SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM origens WHERE nome = 'Assistente de Laboratório'), (SELECT id FROM pericias WHERE nome = 'Misticismo')),
((SELECT id FROM origens WHERE nome = 'Batedor'), (SELECT id FROM pericias WHERE nome = 'Furtividade')),
((SELECT id FROM origens WHERE nome = 'Batedor'), (SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM origens WHERE nome = 'Batedor'), (SELECT id FROM pericias WHERE nome = 'Sobrevivência')),
((SELECT id FROM origens WHERE nome = 'Capanga'), (SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM origens WHERE nome = 'Capanga'), (SELECT id FROM pericias WHERE nome = 'Intimidação')),
((SELECT id FROM origens WHERE nome = 'Charlatão'), (SELECT id FROM pericias WHERE nome = 'Enganação')),
((SELECT id FROM origens WHERE nome = 'Charlatão'), (SELECT id FROM pericias WHERE nome = 'Jogatina')),
((SELECT id FROM origens WHERE nome = 'Circense'), (SELECT id FROM pericias WHERE nome = 'Acrobacia')),
((SELECT id FROM origens WHERE nome = 'Circense'), (SELECT id FROM pericias WHERE nome = 'Atuação')),
((SELECT id FROM origens WHERE nome = 'Circense'), (SELECT id FROM pericias WHERE nome = 'Reflexos')),
((SELECT id FROM origens WHERE nome = 'Criminoso'), (SELECT id FROM pericias WHERE nome = 'Enganação')),
((SELECT id FROM origens WHERE nome = 'Criminoso'), (SELECT id FROM pericias WHERE nome = 'Furtividade')),
((SELECT id FROM origens WHERE nome = 'Criminoso'), (SELECT id FROM pericias WHERE nome = 'Ladinagem')),
((SELECT id FROM origens WHERE nome = 'Curandeiro'), (SELECT id FROM pericias WHERE nome = 'Cura')),
((SELECT id FROM origens WHERE nome = 'Curandeiro'), (SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM origens WHERE nome = 'Eremita'), (SELECT id FROM pericias WHERE nome = 'Misticismo')),
((SELECT id FROM origens WHERE nome = 'Eremita'), (SELECT id FROM pericias WHERE nome = 'Religião')),
((SELECT id FROM origens WHERE nome = 'Eremita'), (SELECT id FROM pericias WHERE nome = 'Sobrevivência')),
((SELECT id FROM origens WHERE nome = 'Escravo'), (SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM origens WHERE nome = 'Escravo'), (SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM origens WHERE nome = 'Escravo'), (SELECT id FROM pericias WHERE nome = 'Furtividade')),
((SELECT id FROM origens WHERE nome = 'Estudioso'), (SELECT id FROM pericias WHERE nome = 'Conhecimento')),
((SELECT id FROM origens WHERE nome = 'Estudioso'), (SELECT id FROM pericias WHERE nome = 'Guerra')),
((SELECT id FROM origens WHERE nome = 'Estudioso'), (SELECT id FROM pericias WHERE nome = 'Misticismo')),
((SELECT id FROM origens WHERE nome = 'Fazendeiro'), (SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM origens WHERE nome = 'Fazendeiro'), (SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM origens WHERE nome = 'Fazendeiro'), (SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM origens WHERE nome = 'Fazendeiro'), (SELECT id FROM pericias WHERE nome = 'Sobrevivência')),
((SELECT id FROM origens WHERE nome = 'Forasteiro'), (SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM origens WHERE nome = 'Forasteiro'), (SELECT id FROM pericias WHERE nome = 'Pilotagem')),
((SELECT id FROM origens WHERE nome = 'Forasteiro'), (SELECT id FROM pericias WHERE nome = 'Sobrevivência')),
((SELECT id FROM origens WHERE nome = 'Gladiador'), (SELECT id FROM pericias WHERE nome = 'Atuação')),
((SELECT id FROM origens WHERE nome = 'Gladiador'), (SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM origens WHERE nome = 'Guarda'), (SELECT id FROM pericias WHERE nome = 'Investigação')),
((SELECT id FROM origens WHERE nome = 'Guarda'), (SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM origens WHERE nome = 'Guarda'), (SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM origens WHERE nome = 'Herdeiro'), (SELECT id FROM pericias WHERE nome = 'Misticismo')),
((SELECT id FROM origens WHERE nome = 'Herdeiro'), (SELECT id FROM pericias WHERE nome = 'Nobreza')),
((SELECT id FROM origens WHERE nome = 'Herdeiro'), (SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM origens WHERE nome = 'Herói Camponês'), (SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM origens WHERE nome = 'Herói Camponês'), (SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM origens WHERE nome = 'Marujo'), (SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM origens WHERE nome = 'Marujo'), (SELECT id FROM pericias WHERE nome = 'Jogatina')),
((SELECT id FROM origens WHERE nome = 'Marujo'), (SELECT id FROM pericias WHERE nome = 'Pilotagem')),
((SELECT id FROM origens WHERE nome = 'Mateiro'), (SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM origens WHERE nome = 'Mateiro'), (SELECT id FROM pericias WHERE nome = 'Furtividade')),
((SELECT id FROM origens WHERE nome = 'Mateiro'), (SELECT id FROM pericias WHERE nome = 'Sobrevivência')),
((SELECT id FROM origens WHERE nome = 'Membro de Guilda'), (SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM origens WHERE nome = 'Membro de Guilda'), (SELECT id FROM pericias WHERE nome = 'Enganação')),
((SELECT id FROM origens WHERE nome = 'Membro de Guilda'), (SELECT id FROM pericias WHERE nome = 'Misticismo')),
((SELECT id FROM origens WHERE nome = 'Membro de Guilda'), (SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM origens WHERE nome = 'Mercador'), (SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM origens WHERE nome = 'Mercador'), (SELECT id FROM pericias WHERE nome = 'Intuição')),
((SELECT id FROM origens WHERE nome = 'Mercador'), (SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM origens WHERE nome = 'Minerador'), (SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM origens WHERE nome = 'Minerador'), (SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM origens WHERE nome = 'Minerador'), (SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM origens WHERE nome = 'Nômade'), (SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM origens WHERE nome = 'Nômade'), (SELECT id FROM pericias WHERE nome = 'Pilotagem')),
((SELECT id FROM origens WHERE nome = 'Nômade'), (SELECT id FROM pericias WHERE nome = 'Sobrevivência')),
((SELECT id FROM origens WHERE nome = 'Pivete'), (SELECT id FROM pericias WHERE nome = 'Furtividade')),
((SELECT id FROM origens WHERE nome = 'Pivete'), (SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM origens WHERE nome = 'Pivete'), (SELECT id FROM pericias WHERE nome = 'Ladinagem')),
((SELECT id FROM origens WHERE nome = 'Refugiado'), (SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM origens WHERE nome = 'Refugiado'), (SELECT id FROM pericias WHERE nome = 'Reflexos')),
((SELECT id FROM origens WHERE nome = 'Refugiado'), (SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM origens WHERE nome = 'Seguidor'), (SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM origens WHERE nome = 'Seguidor'), (SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM origens WHERE nome = 'Selvagem'), (SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM origens WHERE nome = 'Selvagem'), (SELECT id FROM pericias WHERE nome = 'Reflexos')),
((SELECT id FROM origens WHERE nome = 'Selvagem'), (SELECT id FROM pericias WHERE nome = 'Sobrevivência')),
((SELECT id FROM origens WHERE nome = 'Soldado'), (SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM origens WHERE nome = 'Soldado'), (SELECT id FROM pericias WHERE nome = 'Guerra')),
((SELECT id FROM origens WHERE nome = 'Soldado'), (SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM origens WHERE nome = 'Soldado'), (SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM origens WHERE nome = 'Taverneiro'), (SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM origens WHERE nome = 'Taverneiro'), (SELECT id FROM pericias WHERE nome = 'Jogatina')),
((SELECT id FROM origens WHERE nome = 'Taverneiro'), (SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM origens WHERE nome = 'Trabalhador'), (SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM origens WHERE nome = 'Trabalhador'), (SELECT id FROM pericias WHERE nome = 'Fortitude'));

-- Populando as perícias automáticas das classes
INSERT INTO classe_pericias_automaticas (classe_id, pericia_id) VALUES
((SELECT id FROM classes WHERE nome = 'Arcanista'), (SELECT id FROM pericias WHERE nome = 'Misticismo')),
((SELECT id FROM classes WHERE nome = 'Arcanista'), (SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'), (SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'), (SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Bardo'), (SELECT id FROM pericias WHERE nome = 'Atuação')),
((SELECT id FROM classes WHERE nome = 'Bardo'), (SELECT id FROM pericias WHERE nome = 'Reflexos')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'), (SELECT id FROM pericias WHERE nome = 'Reflexos')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'), (SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'), (SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Caçador'), (SELECT id FROM pericias WHERE nome = 'Sobrevivência')),
((SELECT id FROM classes WHERE nome = 'Caçador'), (SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Caçador'), (SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'), (SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'), (SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Clérigo'), (SELECT id FROM pericias WHERE nome = 'Religião')),
((SELECT id FROM classes WHERE nome = 'Clérigo'), (SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM classes WHERE nome = 'Druida'), (SELECT id FROM pericias WHERE nome = 'Sobrevivência')),
((SELECT id FROM classes WHERE nome = 'Druida'), (SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'), (SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'), (SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'), (SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Inventor'), (SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Inventor'), (SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM classes WHERE nome = 'Ladino'), (SELECT id FROM pericias WHERE nome = 'Ladinagem')),
((SELECT id FROM classes WHERE nome = 'Ladino'), (SELECT id FROM pericias WHERE nome = 'Reflexos')),
((SELECT id FROM classes WHERE nome = 'Lutador'), (SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM classes WHERE nome = 'Lutador'), (SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Nobre'), (SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM classes WHERE nome = 'Nobre'), (SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM classes WHERE nome = 'Nobre'), (SELECT id FROM pericias WHERE nome = 'Intimidação')),
((SELECT id FROM classes WHERE nome = 'Paladino'), (SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Paladino'), (SELECT id FROM pericias WHERE nome = 'Vontade'));

-- Populando a tabela classe_pericias_disponiveis
INSERT INTO classe_pericias_disponiveis (classe_id, pericia_id) VALUES
((SELECT id FROM classes WHERE nome = 'Arcanista'),(SELECT id FROM pericias WHERE nome = 'Conhecimento')),
((SELECT id FROM classes WHERE nome = 'Arcanista'),(SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM classes WHERE nome = 'Arcanista'),(SELECT id FROM pericias WHERE nome = 'Enganação')),
((SELECT id FROM classes WHERE nome = 'Arcanista'),(SELECT id FROM pericias WHERE nome = 'Guerra')),
((SELECT id FROM classes WHERE nome = 'Arcanista'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Arcanista'),(SELECT id FROM pericias WHERE nome = 'Intimidação')),
((SELECT id FROM classes WHERE nome = 'Arcanista'),(SELECT id FROM pericias WHERE nome = 'Intuição')),
((SELECT id FROM classes WHERE nome = 'Arcanista'),(SELECT id FROM pericias WHERE nome = 'Investigação')),
((SELECT id FROM classes WHERE nome = 'Arcanista'),(SELECT id FROM pericias WHERE nome = 'Nobreza')),
((SELECT id FROM classes WHERE nome = 'Arcanista'),(SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Arcanista'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'),(SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'),(SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'),(SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'),(SELECT id FROM pericias WHERE nome = 'Intimidação')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'),(SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'),(SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'),(SELECT id FROM pericias WHERE nome = 'Sobrevivência')),
((SELECT id FROM classes WHERE nome = 'Bárbaro'),(SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Acrobacia')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Conhecimento')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Enganação')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Furtividade')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Intuição')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Investigação')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Jogatina')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Ladinagem')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Misticismo')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Nobreza')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Bardo'),(SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Acrobacia')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Atuação')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Enganação')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Furtividade')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Intimidação')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Jogatina')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Pilotagem')),
((SELECT id FROM classes WHERE nome = 'Bucaneiro'),(SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Cura')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Furtividade')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Investigação')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Caçador'),(SELECT id FROM pericias WHERE nome = 'Reflexos')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'),(SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'),(SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'),(SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'),(SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'),(SELECT id FROM pericias WHERE nome = 'Guerra')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'),(SELECT id FROM pericias WHERE nome = 'Intimidação')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'),(SELECT id FROM pericias WHERE nome = 'Nobreza')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Cavaleiro'),(SELECT id FROM pericias WHERE nome = 'Vontade')),
((SELECT id FROM classes WHERE nome = 'Clérigo'),(SELECT id FROM pericias WHERE nome = 'Conhecimento')),
((SELECT id FROM classes WHERE nome = 'Clérigo'),(SELECT id FROM pericias WHERE nome = 'Cura')),
((SELECT id FROM classes WHERE nome = 'Clérigo'),(SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM classes WHERE nome = 'Clérigo'),(SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM classes WHERE nome = 'Clérigo'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Clérigo'),(SELECT id FROM pericias WHERE nome = 'Intuição')),
((SELECT id FROM classes WHERE nome = 'Clérigo'),(SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Clérigo'),(SELECT id FROM pericias WHERE nome = 'Misticismo')),
((SELECT id FROM classes WHERE nome = 'Clérigo'),(SELECT id FROM pericias WHERE nome = 'Nobreza')),
((SELECT id FROM classes WHERE nome = 'Clérigo'),(SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Clérigo'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Conhecimento')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Cura')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Intuição')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Misticismo')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Druida'),(SELECT id FROM pericias WHERE nome = 'Religião')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'),(SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'),(SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'),(SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'),(SELECT id FROM pericias WHERE nome = 'Guerra')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'),(SELECT id FROM pericias WHERE nome = 'Intimidação')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'),(SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'),(SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'),(SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Guerreiro'),(SELECT id FROM pericias WHERE nome = 'Reflexos')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Conhecimento')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Cura')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Investigação')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Misticismo')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Pilotagem')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Inventor'),(SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Acrobacia')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Atuação')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Conhecimento')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Enganação')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Furtividade')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Intimidação')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Intuição')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Investigação')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Jogatina')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Pilotagem')),
((SELECT id FROM classes WHERE nome = 'Ladino'),(SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Lutador'),(SELECT id FROM pericias WHERE nome = 'Acrobacia')),
((SELECT id FROM classes WHERE nome = 'Lutador'),(SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM classes WHERE nome = 'Lutador'),(SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM classes WHERE nome = 'Lutador'),(SELECT id FROM pericias WHERE nome = 'Enganação')),
((SELECT id FROM classes WHERE nome = 'Lutador'),(SELECT id FROM pericias WHERE nome = 'Furtividade')),
((SELECT id FROM classes WHERE nome = 'Lutador'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Lutador'),(SELECT id FROM pericias WHERE nome = 'Intimidação')),
((SELECT id FROM classes WHERE nome = 'Lutador'),(SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Lutador'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Lutador'),(SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Lutador'),(SELECT id FROM pericias WHERE nome = 'Reflexos')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Atuação')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Conhecimento')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Enganação')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Guerra')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Intimidação')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Intuição')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Investigação')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Jogatina')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Luta')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Nobreza')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Ofício')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Nobre'),(SELECT id FROM pericias WHERE nome = 'Pontaria')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Adestramento')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Atletismo')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Cavalgar')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Cura')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Diplomacia')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Fortitude')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Guerra')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Iniciativa')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Intuição')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Nobreza')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Percepção')),
((SELECT id FROM classes WHERE nome = 'Paladino'),(SELECT id FROM pericias WHERE nome = 'Religião'));
