-- Tabela para todos os poderes (Gerais e de Origens)
CREATE TABLE IF NOT EXISTS poderes (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao TEXT,
    tipo VARCHAR(50), -- Combate, Destino, Magia, Origem
    requisitos TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    deleted_at TIMESTAMP
);

-- Seed para a tabela de poderes
INSERT INTO poderes (nome, descricao, tipo, requisitos) VALUES
-- Poderes de Origem
('Membro da Igreja', 'Você consegue hospedagem confortável e informação em qualquer templo de sua divindade, para você e seus aliados.', 'Origem', 'Origem: Acólito'),
('Amigo Especial', 'Você recebe +5 em testes de Adestramento com animais e possui um parceiro animal que fornece +2 em uma perícia a sua escolha (exceto Luta ou Pontaria).', 'Origem', 'Origem: Amigo dos Animais'),
('Lembranças Graduais', 'Durante suas aventuras, a critério do mestre, você pode fazer um teste de Sabedoria (CD 10) para reconhecer pessoas, lugares ou criaturas do seu passado.', 'Origem', 'Origem: Amnésico'),
('Sangue Azul', 'Você tem alguma influência política, suficiente para ser tratado com mais leniência pela guarda, conseguir uma audiência com o nobre local etc.', 'Origem', 'Origem: Aristocrata'),
('Frutos do Trabalho', 'No início de cada aventura, você recebe até 5 itens gerais que possa fabricar num valor total de até T$ 50. Esse valor aumenta com os patamares.', 'Origem', 'Origem: Artesão'),
('Dom Artístico', 'Você recebe +2 em testes de Atuação, e recebe o dobro de tibares em apresentações.', 'Origem', 'Origem: Artista'),
('Esse Cheiro...', 'Você recebe +2 em Fortitude e detecta automaticamente a presença de itens alquímicos em alcance curto.', 'Origem', 'Origem: Assistente de Laboratório'),
('À Prova de Tudo', 'Você não sofre penalidade em deslocamento e Sobrevivência por clima ruim e por terreno difícil natural.', 'Origem', 'Origem: Batedor'),
('Confissão', 'Você pode usar Intimidação para interrogar sem custo e em um minuto (veja Investigação).', 'Origem', 'Origem: Capanga'),
('Alpinista Social', 'Você pode substituir testes de Diplomacia por testes de Enganação.', 'Origem', 'Origem: Charlatão'),
('Truque de Mágica', 'Você pode lançar Explosão de Chamas, Hipnotismo e Queda Suave, mas apenas com o aprimoramento Truque. Esta não é uma habilidade mágica.', 'Origem', 'Origem: Circense'),
('Punguista', 'Você pode fazer testes de Ladinagem para sustento (como a perícia Ofício), mas em apenas um dia. Se passar, recebe o dobro do dinheiro.', 'Origem', 'Origem: Criminoso'),
('Médico de Campo', 'Você soma sua Sabedoria aos PV restaurados por suas habilidades e itens mundanos de cura.', 'Origem', 'Origem: Curandeiro'),
('Busca Interior', 'Quando você e seus companheiros estão diante de um mistério, você pode gastar 1 PM para meditar sozinho e receber uma dica do mestre.', 'Origem', 'Origem: Eremita'),
('Desejo de Liberdade', 'Você recebe +5 em testes contra a manobra agarrar e efeitos de movimento.', 'Origem', 'Origem: Escravo'),
('Palpite Fundamentado', 'Quando vai fazer um teste de perícia baseada em Inteligência ou Sabedoria, você pode gastar 2 PM para substituí-la por Conhecimento.', 'Origem', 'Origem: Estudioso'),
('Água no Feijão', 'Você não sofre a penalidade de -5 e não gasta matéria-prima adicional para fabricar pratos para cinco pessoas.', 'Origem', 'Origem: Fazendeiro'),
('Cultura Exótica', 'Quando vai fazer um teste de perícia que requer treinamento, você pode gastar 1 PM para ignorar esse requerimento para esse teste.', 'Origem', 'Origem: Forasteiro'),
('Pão e Circo', 'Você pode escolher causar dano não letal sem sofrer a penalidade de -5.', 'Origem', 'Origem: Gladiador'),
('Detetive', 'Você pode gastar 1 PM para substituir testes de Percepção e Intuição por testes de Investigação até o fim da cena.', 'Origem', 'Origem: Guarda'),
('Herança', 'Você herdou um item de preço de até T$ 1.000. Você pode escolher este poder duas vezes, para um item de até T$ 2.000.', 'Origem', 'Origem: Herdeiro'),
('Coração Heroico', 'Você recebe +3 pontos de mana. Quando atinge um novo patamar, recebe +3 PM.', 'Origem', 'Origem: Herói Camponês'),
('Passagem de Navio', 'Você consegue transporte marítimo para você e seus aliados, sem custos, desde que todos paguem com trabalho.', 'Origem', 'Origem: Marujo'),
('Vendedor de Carcaças', 'Você pode extrair recursos de criaturas em um minuto, em vez de uma hora, e recebe +5 no teste.', 'Origem', 'Origem: Mateiro'),
('Rede de Contatos', 'Graças à influência de sua guilda, você pode usar Diplomacia para interrogar sem custo e em um minuto.', 'Origem', 'Origem: Membro de Guilda'),
('Negociação', 'Você pode vender itens 10% mais caro (não cumulativo com barganha).', 'Origem', 'Origem: Mercador'),
('Escavador', 'Você se torna proficiente em picaretas, causa +1 de dano com elas e não é afetado por terreno difícil em masmorras e subterrâneos.', 'Origem', 'Origem: Minerador'),
('Mochileiro', 'Seu limite de carga aumenta em 5 espaços.', 'Origem', 'Origem: Nômade'),
('Quebra-Galho', 'Em cidades ou metrópoles, você pode comprar qualquer item mundano não superior por metade do preço normal.', 'Origem', 'Origem: Pivete'),
('Estoico', 'Sua condição de descanso é uma categoria acima do padrão pela situação.', 'Origem', 'Origem: Refugiado'),
('Antigo Mestre', 'Você ainda mantém contato com o herói que costumava servir. Uma vez por aventura, ele surge para ajudá-lo por uma cena como um parceiro mestre.', 'Origem', 'Origem: Seguidor'),
('Vida Rústica', 'Você é imune a efeitos prejudiciais de itens ingeríveis e sua recuperação de PV e PM nunca é inferior ao seu próprio nível, mesmo em descanso ruim.', 'Origem', 'Origem: Selvagem'),
('Influência Militar', 'Onde houver acampamentos ou bases militares, você pode conseguir hospedagem e informações para você e seus aliados.', 'Origem', 'Origem: Soldado'),
('Gororoba', 'Você não sofre a penalidade de -5 para fabricar um prato especial adicional.', 'Origem', 'Origem: Taverneiro'),
('Esforçado', 'Você recebe um bônus de +2 em todos os testes de perícias estendidos (incluindo perigos complexos).', 'Origem', 'Origem: Trabalhador'),

-- Poderes de Combate
('Acuidade com Arma', 'Quando usa uma arma corpo a corpo leve ou uma arma de arremesso, você pode usar sua Destreza em vez de Força nos testes de ataque e rolagens de dano.', 'Combate', 'Des 1'),
('Arma Secundária Grande', 'Você pode empunhar duas armas de uma mão com o poder Estilo de Duas Armas.', 'Combate', 'Estilo de Duas Armas'),
('Arremesso Múltiplo', 'Uma vez por rodada, quando faz um ataque com uma arma de arremesso, você pode gastar 1 PM para fazer um ataque adicional contra o mesmo alvo.', 'Combate', 'Des 1, Estilo de Arremesso'),
('Arremesso Potente', 'Quando usa uma arma de arremesso, pode usar Força em vez de Destreza nos ataques. Permite usar Ataque Poderoso com armas de arremesso.', 'Combate', 'For 1, Estilo de Arremesso'),
('Ataque com Escudo', 'Uma vez por rodada, se estiver usando um escudo e fizer a ação agredir, pode gastar 1 PM para um ataque extra com o escudo.', 'Combate', 'Estilo de Arma e Escudo'),
('Ataque Pesado', 'Ao atacar com arma de duas mãos e acertar, pode pagar 1 PM para fazer uma manobra (derrubar ou empurrar) como ação livre.', 'Combate', 'Estilo de Duas Mãos'),
('Ataque Poderoso', 'Ao fazer um ataque corpo a corpo, pode sofrer –2 no teste de ataque para receber +5 na rolagem de dano.', 'Combate', 'For 1'),
('Ataque Preciso', 'Se estiver empunhando uma arma corpo a corpo em uma mão e nada na outra, recebe +2 na margem de ameaça e +1 no multiplicador de crítico.', 'Combate', 'Estilo de Uma Arma'),
('Bloqueio com Escudo', 'Quando sofre dano, pode gastar 1 PM para receber RD igual ao bônus na Defesa do seu escudo contra este dano.', 'Combate', 'Estilo de Arma e Escudo'),
('Carga de Cavalaria', 'Ao fazer uma investida montada, causa +2d8 de dano e pode continuar se movendo após o ataque.', 'Combate', 'Ginete'),
('Combate Defensivo', 'Ao usar a ação agredir, pode sofrer –2 nos ataques para receber +5 na Defesa até seu próximo turno.', 'Combate', 'Int 1'),
('Derrubar Aprimorado', 'Recebe +2 em testes para derrubar. Ao derrubar uma criatura, pode gastar 1 PM para um ataque extra contra ela.', 'Combate', 'Combate Defensivo'),
('Desarmar Aprimorado', 'Recebe +2 em testes para desarmar. Ao desarmar, pode gastar 1 PM para arremessar a arma do oponente para longe.', 'Combate', 'Combate Defensivo'),
('Disparo Preciso', 'Pode fazer ataques à distância contra oponentes em combate corpo a corpo sem sofrer a penalidade de –5.', 'Combate', 'Estilo de Disparo ou Estilo de Arremesso'),
('Disparo Rápido', 'Se usar uma arma de disparo com recarga livre e gastar uma ação completa para agredir, pode fazer um ataque adicional, sofrendo –2 em todos os ataques.', 'Combate', 'Des 1, Estilo de Disparo'),
('Empunhadura Poderosa', 'A penalidade por usar uma arma de categoria de tamanho maior que a sua diminui para –2.', 'Combate', 'For 3'),
('Encouraçado', 'Se estiver usando armadura pesada, recebe +2 na Defesa. O bônus aumenta em +2 para cada outro poder que tenha Encouraçado como pré-requisito.', 'Combate', 'Proficiência com armaduras pesadas'),
('Esquiva', 'Recebe +2 na Defesa e Reflexos.', 'Combate', 'Des 1'),
('Estilo de Arma e Escudo', 'Se estiver usando um escudo, o bônus na Defesa que ele fornece aumenta em +2.', 'Combate', 'Treinado em Luta, proficiência com escudos'),
('Estilo de Arma Longa', 'Recebe +2 em testes de ataque com armas alongadas e pode atacar alvos adjacentes com elas.', 'Combate', 'For 1, treinado em Luta'),
('Estilo de Arremesso', 'Pode sacar armas de arremesso como ação livre e recebe +2 nas rolagens de dano com elas.', 'Combate', 'Treinado em Pontaria'),
('Estilo de Disparo', 'Se estiver usando uma arma de disparo, soma sua Destreza nas rolagens de dano.', 'Combate', 'Treinado em Pontaria'),
('Estilo de Duas Armas', 'Se estiver empunhando duas armas (uma leve) e fizer a ação agredir, pode fazer dois ataques, um com cada arma, sofrendo –2 em todos os ataques.', 'Combate', 'Des 2, treinado em Luta'),
('Estilo de Duas Mãos', 'Se estiver usando uma arma corpo a corpo com as duas mãos, recebe +5 nas rolagens de dano.', 'Combate', 'For 2, treinado em Luta'),
('Estilo de Uma Arma', 'Se estiver usando uma arma corpo a corpo em uma mão e nada na outra, recebe +2 na Defesa e nos testes de ataque com essa arma.', 'Combate', 'Treinado em Luta'),
('Estilo Desarmado', 'Seus ataques desarmados causam 1d6 de dano e podem ser letais.', 'Combate', 'Treinado em Luta'),
('Fanático', 'Seu deslocamento não é reduzido por usar armaduras pesadas.', 'Combate', '12º nível, Encouraçado'),
('Finta Aprimorada', 'Recebe +2 em testes de Enganação para fintar e pode fintar como uma ação de movimento.', 'Combate', 'Treinado em Enganação'),
('Foco em Arma', 'Escolha uma arma. Recebe +2 em testes de ataque com essa arma.', 'Combate', 'Proficiência com a arma'),
('Ginete', 'Passa automaticamente em testes de Cavalgar para não cair da montaria. Não sofre penalidades para atacar à distância ou lançar magias montado.', 'Combate', 'Treinado em Cavalgar'),
('Inexpugnável', 'Se estiver usando armadura pesada, recebe +2 em todos os testes de resistência.', 'Combate', '6º nível, Encouraçado'),
('Mira Apurada', 'Ao usar a ação mirar, recebe +2 em testes de ataque e na margem de ameaça com ataques à distância até o fim do turno.', 'Combate', 'Sab 1, Disparo Preciso'),
('Piqueiro', 'Uma vez por rodada, se estiver usando uma arma alongada e um inimigo entrar em seu alcance, pode gastar 1 PM para um ataque corpo a corpo contra ele.', 'Combate', 'Estilo de Arma Longa'),
('Presença Aterradora', 'Pode gastar uma ação padrão e 1 PM para assustar todas as criaturas a sua escolha em alcance curto.', 'Combate', 'Treinado em Intimidação'),
('Proficiência', 'Escolha uma proficiência (armas marciais, exóticas, de fogo, armaduras pesadas ou escudos). Você recebe essa proficiência.', 'Combate', 'Nenhum'),
('Quebrar Aprimorado', 'Recebe +2 em testes para quebrar. Ao destruir uma arma, pode gastar 1 PM para um ataque extra contra o usuário dela.', 'Combate', 'Ataque Poderoso'),
('Reflexos de Combate', 'Ganha uma ação de movimento extra no seu primeiro turno de cada combate.', 'Combate', 'Des 1'),
('Saque Rápido', 'Recebe +2 em Iniciativa, pode sacar/guardar itens como ação livre e reduz a ação para recarregar armas de disparo em uma categoria.', 'Combate', 'Treinado em Iniciativa'),
('Trespassar', 'Ao fazer um ataque corpo a corpo e reduzir o alvo a 0 PV ou menos, pode gastar 1 PM para fazer um ataque adicional contra outra criatura em alcance.', 'Combate', 'Ataque Poderoso'),
('Vitalidade', 'Recebe +1 PV por nível de personagem e +2 em Fortitude.', 'Combate', 'Con 1'),

-- Poderes de Destino
('Acrobático', 'Pode usar Destreza em vez de Força em testes de Atletismo. Terreno difícil não reduz seu deslocamento.', 'Destino', 'Des 2'),
('Ao Sabor do Destino', 'Você abre mão de usar itens mágicos permanentes em troca de bônus que aumentam com o nível (em perícias, Defesa, dano e atributos).', 'Destino', '6º nível de personagem'),
('Aparência Inofensiva', 'A primeira criatura inteligente que atacar você em uma cena deve fazer um teste de Vontade (CD Car) ou perderá a ação.', 'Destino', 'Car 1'),
('Atlético', 'Recebe +2 em Atletismo e +3m em seu deslocamento.', 'Destino', 'For 2'),
('Atraente', 'Recebe +2 em testes de perícias baseadas em Carisma contra criaturas que possam se sentir fisicamente atraídas por você.', 'Destino', 'Car 1'),
('Comandar', 'Pode gastar uma ação de movimento e 1 PM para conceder +1 em testes de perícia para aliados em alcance médio até o fim da cena.', 'Destino', 'Car 1'),
('Costas Largas', 'Seu limite de carga aumenta em 5 espaços e você pode se beneficiar de um item vestido adicional.', 'Destino', 'Con 1, For 1'),
('Foco em Perícia', 'Escolha uma perícia. Ao fazer um teste dela, pode gastar 1 PM para rolar dois dados e usar o melhor resultado.', 'Destino', 'Treinado na perícia escolhida'),
('Inventário Organizado', 'Soma sua Inteligência no limite de espaços que pode carregar. Itens de meio espaço ocupam 1/4 de espaço para você.', 'Destino', 'Int 1'),
('Investigador', 'Recebe +2 em Investigação e soma sua Inteligência em Intuição.', 'Destino', 'Int 1'),
('Lobo Solitário', 'Recebe +1 em testes de perícia e Defesa se estiver sem nenhum aliado em alcance curto. Não sofre penalidade por usar Cura em si mesmo.', 'Destino', 'Nenhum'),
('Medicina', 'Pode gastar uma ação completa para fazer um teste de Cura (CD 15) em uma criatura. Se passar, ela recupera 1d6 PV, mais 1d6 para cada 5 pontos de excesso. Só pode ser usado uma vez por dia na mesma criatura.', 'Destino', 'Sab 1, treinado em Cura'),
('Parceiro', 'Você possui um parceiro animal ou humanoide iniciante de um tipo a sua escolha.', 'Destino', 'Treinado em Adestramento ou Diplomacia, 5º nível'),
('Sentidos Aguçados', 'Recebe +2 em Percepção, não fica desprevenido contra inimigos que não possa ver e pode rolar novamente a chance de falha por camuflagem.', 'Destino', 'Sab 1, treinado em Percepção'),
('Sortudo', 'Quando faz um teste, pode gastar 3 PM para rolá-lo novamente.', 'Destino', 'Nenhum'),
('Surto Heroico', 'Uma vez por rodada, pode gastar 5 PM para realizar uma ação padrão ou de movimento adicional.', 'Destino', 'Nenhum'),
('Torcida', 'Recebe +2 em testes de perícia e Defesa quando tem a torcida a seu favor.', 'Destino', 'Car 1'),
('Treinamento em Perícia', 'Você se torna treinado em uma perícia a sua escolha.', 'Destino', 'Nenhum'),
('Venefício', 'Quando usa um veneno, não corre risco de se envenenar. A CD para resistir aos seus venenos aumenta em +2.', 'Destino', 'Treinado em Ofício (alquimista)'),
('Vontade de Ferro', 'Recebe +1 PM para cada dois níveis de personagem e +2 em Vontade.', 'Destino', 'Sab 1'),

-- Poderes de Magia
('Celebrar Ritual', 'Pode lançar magias como rituais, dobrando seu limite de PM, mas com execução de 1 hora e custo em T$.', 'Magia', 'Lançar magias, treinado em Misticismo ou Religião, 8º nível'),
('Escrever Pergaminho', 'Pode usar Ofício (escriba) para fabricar pergaminhos com magias que conheça.', 'Magia', 'Habilidade Magias, treinado em Ofício (escriba)'),
('Foco em Magia', 'Escolha uma magia que possa lançar. Seu custo diminui em –1 PM.', 'Magia', 'Lançar magias'),
('Magia Acelerada', 'APRIMORAMENTO. Muda a execução da magia para ação livre. Custo: +4 PM.', 'Magia', 'Lançar magias de 2º círculo'),
('Magia Ampliada', 'APRIMORAMENTO. Aumenta o alcance da magia em um passo ou dobra sua área de efeito. Custo: +2 PM.', 'Magia', 'Lançar magias'),
('Magia Discreta', 'APRIMORAMENTO. Você lança a magia sem componentes verbais ou gestuais. Custo: +2 PM.', 'Magia', 'Lançar magias'),
('Magia Ilimitada', 'Você soma seu atributo-chave no limite de PM que pode gastar numa magia.', 'Magia', 'Lançar magias'),
('Preparar Poção', 'Pode usar Ofício (alquimista) para fabricar poções de 1º e 2º círculos com magias que conheça.', 'Magia', 'Habilidade Magias, treinado em Ofício (alquimista)');

-- Seed para a tabela 'poderes' com os Poderes da Tormenta
INSERT INTO poderes (nome, descricao, tipo, requisitos) VALUES
('Anatomia Insana', 'Você tem 25% de chance (resultado “1” em 1d4) de ignorar o dano adicional de um acerto crítico ou ataque furtivo. A chance aumenta em +25% para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', NULL),
('Antenas', 'Você recebe +1 em Iniciativa, Percepção e Vontade. Este bônus aumenta em +1 para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', NULL),
('Armamento Aberrante', 'Você pode gastar uma ação de movimento e 1 PM para produzir uma versão orgânica de qualquer arma corpo a corpo ou de arremesso com a qual seja proficiente. O dano da arma aumenta em um passo para cada dois outros poderes da Tormenta que você possui. A arma dura pela cena.', 'Tormenta', 'Outro poder da Tormenta'),
('Articulações Flexíveis', 'Você recebe +1 em Acrobacia, Furtividade e Reflexos. Este bônus aumenta em +1 para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', NULL),
('Asas Insetoides', 'Você pode gastar 1 PM para receber deslocamento de voo 9m até o fim do seu turno. O deslocamento aumenta em +1,5m para cada outro poder da Tormenta que você possui.', 'Tormenta', 'Quatro outros poderes da Tormenta'),
('Carapaça', 'Sua pele é recoberta por placas quitinosas. Você recebe +1 na Defesa. Este bônus aumenta em +1 para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', NULL),
('Corpo Aberrante', 'Seu dano desarmado aumenta em um passo, mais um passo para cada quatro outros poderes da Tormenta que você possui.', 'Tormenta', 'Outro poder da Tormenta'),
('Cuspir Enxame', 'Você pode gastar uma ação completa e 2 PM para criar um enxame de insetos rubros em alcance curto com duração sustentada. O enxame causa 2d6 de dano de ácido a criaturas no espaço dele. O dano aumenta em +1d6 para cada 1 PM extra gasto (limitado por cada dois outros poderes da Tormenta que possui).', 'Tormenta', NULL),
('Dentes Afiados', 'Você recebe uma arma natural de mordida (dano 1d4, crítico x2, corte). Uma vez por rodada, quando usa a ação agredir, pode gastar 1 PM para fazer um ataque corpo a corpo extra com a mordida.', 'Tormenta', NULL),
('Desprezar a Realidade', 'Você pode gastar 2 PM para ignorar terreno difícil e causar 20% de chance de falha em efeitos usados contra você até o início de seu próximo turno. A chance aumenta em 5% para cada dois outros poderes da Tormenta que você possuir (máximo 50%).', 'Tormenta', 'Quatro outros poderes da Tormenta'),
('Empunhadura Rubra', 'Você pode gastar 1 PM para cobrir suas mãos com uma carapaça rubra, recebendo +1 em Luta até o final da cena. O bônus aumenta em +1 para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', NULL),
('Fome de Mana', 'Quando passa em um teste de resistência contra uma habilidade mágica de um inimigo, você recebe 1 PM temporário cumulativo. O máximo de PM temporários que pode ganhar por cena desta forma é igual ao número de poderes da Tormenta que possui.', 'Tormenta', NULL),
('Larva Explosiva', 'Se uma criatura que sofreu dano da sua mordida nesta cena for reduzida a 0 PV ou menos, ela explode, causando 4d4 de dano de ácido em criaturas adjacentes. O dano aumenta em +2d4 para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', 'Dentes Afiados'),
('Legião Aberrante', 'Seu corpo se transforma em uma massa de insetos. Você pode atravessar espaços pequenos e recebe +1 em testes contra manobras de combate e de resistência contra efeitos que tenham você como alvo. O bônus aumenta em +1 para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', 'Anatomia Insana, três outros poderes da Tormenta'),
('Mãos Membranosas', 'Você recebe +1 em Atletismo, Fortitude e testes de agarrar. Este bônus aumenta em +1 para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', NULL),
('Membros Estendidos', 'Seu alcance natural para ataques corpo a corpo aumenta em +1,5m. Para cada quatro outros poderes da Tormenta que você possui, esse alcance aumenta em +1,5m.', 'Tormenta', NULL),
('Membros Extras', 'Você possui duas armas naturais de patas insetoides. Uma vez por rodada, quando usa a ação agredir, pode gastar 2 PM para fazer um ataque corpo a corpo extra com cada uma (dano 1d4, crítico x2, corte).', 'Tormenta', 'Quatro outros poderes da Tormenta'),
('Mente Aberrante', 'Você recebe resistência a efeitos mentais +1. Sempre que precisa fazer um teste de Vontade para resistir a uma habilidade, a criatura que usou a habilidade sofre 1d6 de dano psíquico. O bônus e o dano aumentam em +1 e +1d6, respectivamente, para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', NULL),
('Olhos Vermelhos', 'Você recebe visão no escuro e +1 em Intimidação. Este bônus aumenta em +1 para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', NULL),
('Pele Corrompida', 'Sua carne foi mesclada à matéria vermelha. Você recebe redução de ácido, eletricidade, fogo, frio, luz e trevas 2. Esta RD aumenta em +2 para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', NULL),
('Sangue Ácido', 'Quando você sofre dano por um ataque corpo a corpo, o atacante sofre 1 ponto de dano de ácido por poder da Tormenta que você possui.', 'Tormenta', NULL),
('Visco Rubro', 'Você pode gastar 1 PM para expelir um líquido corrosivo, recebendo +1 nas rolagens de dano corpo a corpo até o final da cena. Este bônus aumenta em +1 para cada dois outros poderes da Tormenta que você possui.', 'Tormenta', NULL);
