-- Tabela para associar origens com seus poderes opcionais
CREATE TABLE IF NOT EXISTS origem_poderes (
    origem_id INTEGER REFERENCES origens(id) ON DELETE CASCADE,
    poder_id INTEGER REFERENCES poderes(id) ON DELETE CASCADE,
    PRIMARY KEY (origem_id, poder_id)
);

-- Seed para a tabela de associação origem_poderes
INSERT INTO origem_poderes (origem_id, poder_id) VALUES
((SELECT id FROM origens WHERE nome = 'Acólito'), (SELECT id FROM poderes WHERE nome = 'Medicina')),
((SELECT id FROM origens WHERE nome = 'Acólito'), (SELECT id FROM poderes WHERE nome = 'Membro da Igreja')),
((SELECT id FROM origens WHERE nome = 'Acólito'), (SELECT id FROM poderes WHERE nome = 'Vontade de Ferro')),
((SELECT id FROM origens WHERE nome = 'Amigo dos Animais'), (SELECT id FROM poderes WHERE nome = 'Amigo Especial')),
((SELECT id FROM origens WHERE nome = 'Amnésico'), (SELECT id FROM poderes WHERE nome = 'Lembranças Graduais')),
((SELECT id FROM origens WHERE nome = 'Aristocrata'), (SELECT id FROM poderes WHERE nome = 'Comandar')),
((SELECT id FROM origens WHERE nome = 'Aristocrata'), (SELECT id FROM poderes WHERE nome = 'Sangue Azul')),
((SELECT id FROM origens WHERE nome = 'Artesão'), (SELECT id FROM poderes WHERE nome = 'Frutos do Trabalho')),
((SELECT id FROM origens WHERE nome = 'Artesão'), (SELECT id FROM poderes WHERE nome = 'Sortudo')),
((SELECT id FROM origens WHERE nome = 'Artista'), (SELECT id FROM poderes WHERE nome = 'Atraente')),
((SELECT id FROM origens WHERE nome = 'Artista'), (SELECT id FROM poderes WHERE nome = 'Dom Artístico')),
((SELECT id FROM origens WHERE nome = 'Artista'), (SELECT id FROM poderes WHERE nome = 'Sortudo')),
((SELECT id FROM origens WHERE nome = 'Artista'), (SELECT id FROM poderes WHERE nome = 'Torcida')),
((SELECT id FROM origens WHERE nome = 'Assistente de Laboratório'), (SELECT id FROM poderes WHERE nome = 'Esse Cheiro...')),
((SELECT id FROM origens WHERE nome = 'Assistente de Laboratório'), (SELECT id FROM poderes WHERE nome = 'Venefício')),
((SELECT id FROM origens WHERE nome = 'Batedor'), (SELECT id FROM poderes WHERE nome = 'À Prova de Tudo')),
((SELECT id FROM origens WHERE nome = 'Batedor'), (SELECT id FROM poderes WHERE nome = 'Estilo de Disparo')),
((SELECT id FROM origens WHERE nome = 'Batedor'), (SELECT id FROM poderes WHERE nome = 'Sentidos Aguçados')),
((SELECT id FROM origens WHERE nome = 'Capanga'), (SELECT id FROM poderes WHERE nome = 'Confissão')),
((SELECT id FROM origens WHERE nome = 'Charlatão'), (SELECT id FROM poderes WHERE nome = 'Alpinista Social')),
((SELECT id FROM origens WHERE nome = 'Charlatão'), (SELECT id FROM poderes WHERE nome = 'Aparência Inofensiva')),
((SELECT id FROM origens WHERE nome = 'Charlatão'), (SELECT id FROM poderes WHERE nome = 'Sortudo')),
((SELECT id FROM origens WHERE nome = 'Circense'), (SELECT id FROM poderes WHERE nome = 'Acrobático')),
((SELECT id FROM origens WHERE nome = 'Circense'), (SELECT id FROM poderes WHERE nome = 'Torcida')),
((SELECT id FROM origens WHERE nome = 'Circense'), (SELECT id FROM poderes WHERE nome = 'Truque de Mágica')),
((SELECT id FROM origens WHERE nome = 'Criminoso'), (SELECT id FROM poderes WHERE nome = 'Punguista')),
((SELECT id FROM origens WHERE nome = 'Criminoso'), (SELECT id FROM poderes WHERE nome = 'Venefício')),
((SELECT id FROM origens WHERE nome = 'Curandeiro'), (SELECT id FROM poderes WHERE nome = 'Medicina')),
((SELECT id FROM origens WHERE nome = 'Curandeiro'), (SELECT id FROM poderes WHERE nome = 'Médico de Campo')),
((SELECT id FROM origens WHERE nome = 'Curandeiro'), (SELECT id FROM poderes WHERE nome = 'Venefício')),
((SELECT id FROM origens WHERE nome = 'Eremita'), (SELECT id FROM poderes WHERE nome = 'Busca Interior')),
((SELECT id FROM origens WHERE nome = 'Eremita'), (SELECT id FROM poderes WHERE nome = 'Lobo Solitário')),
((SELECT id FROM origens WHERE nome = 'Escravo'), (SELECT id FROM poderes WHERE nome = 'Desejo de Liberdade')),
((SELECT id FROM origens WHERE nome = 'Escravo'), (SELECT id FROM poderes WHERE nome = 'Vitalidade')),
((SELECT id FROM origens WHERE nome = 'Estudioso'), (SELECT id FROM poderes WHERE nome = 'Aparência Inofensiva')),
((SELECT id FROM origens WHERE nome = 'Estudioso'), (SELECT id FROM poderes WHERE nome = 'Palpite Fundamentado')),
((SELECT id FROM origens WHERE nome = 'Fazendeiro'), (SELECT id FROM poderes WHERE nome = 'Água no Feijão')),
((SELECT id FROM origens WHERE nome = 'Fazendeiro'), (SELECT id FROM poderes WHERE nome = 'Ginete')),
((SELECT id FROM origens WHERE nome = 'Forasteiro'), (SELECT id FROM poderes WHERE nome = 'Cultura Exótica')),
((SELECT id FROM origens WHERE nome = 'Forasteiro'), (SELECT id FROM poderes WHERE nome = 'Lobo Solitário')),
((SELECT id FROM origens WHERE nome = 'Gladiador'), (SELECT id FROM poderes WHERE nome = 'Atraente')),
((SELECT id FROM origens WHERE nome = 'Gladiador'), (SELECT id FROM poderes WHERE nome = 'Pão e Circo')),
((SELECT id FROM origens WHERE nome = 'Gladiador'), (SELECT id FROM poderes WHERE nome = 'Torcida')),
((SELECT id FROM origens WHERE nome = 'Guarda'), (SELECT id FROM poderes WHERE nome = 'Detetive')),
((SELECT id FROM origens WHERE nome = 'Guarda'), (SELECT id FROM poderes WHERE nome = 'Investigador')),
((SELECT id FROM origens WHERE nome = 'Herdeiro'), (SELECT id FROM poderes WHERE nome = 'Comandar')),
((SELECT id FROM origens WHERE nome = 'Herdeiro'), (SELECT id FROM poderes WHERE nome = 'Herança')),
((SELECT id FROM origens WHERE nome = 'Herói Camponês'), (SELECT id FROM poderes WHERE nome = 'Coração Heroico')),
((SELECT id FROM origens WHERE nome = 'Herói Camponês'), (SELECT id FROM poderes WHERE nome = 'Sortudo')),
((SELECT id FROM origens WHERE nome = 'Herói Camponês'), (SELECT id FROM poderes WHERE nome = 'Surto Heroico')),
((SELECT id FROM origens WHERE nome = 'Herói Camponês'), (SELECT id FROM poderes WHERE nome = 'Torcida')),
((SELECT id FROM origens WHERE nome = 'Marujo'), (SELECT id FROM poderes WHERE nome = 'Acrobático')),
((SELECT id FROM origens WHERE nome = 'Marujo'), (SELECT id FROM poderes WHERE nome = 'Passagem de Navio')),
((SELECT id FROM origens WHERE nome = 'Mateiro'), (SELECT id FROM poderes WHERE nome = 'Lobo Solitário')),
((SELECT id FROM origens WHERE nome = 'Mateiro'), (SELECT id FROM poderes WHERE nome = 'Sentidos Aguçados')),
((SELECT id FROM origens WHERE nome = 'Mateiro'), (SELECT id FROM poderes WHERE nome = 'Vendedor de Carcaças')),
((SELECT id FROM origens WHERE nome = 'Membro de Guilda'), (SELECT id FROM poderes WHERE nome = 'Foco em Perícia')),
((SELECT id FROM origens WHERE nome = 'Membro de Guilda'), (SELECT id FROM poderes WHERE nome = 'Rede de Contatos')),
((SELECT id FROM origens WHERE nome = 'Mercador'), (SELECT id FROM poderes WHERE nome = 'Negociação')),
((SELECT id FROM origens WHERE nome = 'Mercador'), (SELECT id FROM poderes WHERE nome = 'Proficiência')),
((SELECT id FROM origens WHERE nome = 'Mercador'), (SELECT id FROM poderes WHERE nome = 'Sortudo')),
((SELECT id FROM origens WHERE nome = 'Minerador'), (SELECT id FROM poderes WHERE nome = 'Ataque Poderoso')),
((SELECT id FROM origens WHERE nome = 'Minerador'), (SELECT id FROM poderes WHERE nome = 'Escavador')),
((SELECT id FROM origens WHERE nome = 'Minerador'), (SELECT id FROM poderes WHERE nome = 'Sentidos Aguçados')),
((SELECT id FROM origens WHERE nome = 'Nômade'), (SELECT id FROM poderes WHERE nome = 'Lobo Solitário')),
((SELECT id FROM origens WHERE nome = 'Nômade'), (SELECT id FROM poderes WHERE nome = 'Mochileiro')),
((SELECT id FROM origens WHERE nome = 'Nômade'), (SELECT id FROM poderes WHERE nome = 'Sentidos Aguçados')),
((SELECT id FROM origens WHERE nome = 'Pivete'), (SELECT id FROM poderes WHERE nome = 'Acrobático')),
((SELECT id FROM origens WHERE nome = 'Pivete'), (SELECT id FROM poderes WHERE nome = 'Aparência Inofensiva')),
((SELECT id FROM origens WHERE nome = 'Pivete'), (SELECT id FROM poderes WHERE nome = 'Quebra-Galho')),
((SELECT id FROM origens WHERE nome = 'Refugiado'), (SELECT id FROM poderes WHERE nome = 'Estoico')),
((SELECT id FROM origens WHERE nome = 'Refugiado'), (SELECT id FROM poderes WHERE nome = 'Vontade de Ferro')),
((SELECT id FROM origens WHERE nome = 'Seguidor'), (SELECT id FROM poderes WHERE nome = 'Antigo Mestre')),
((SELECT id FROM origens WHERE nome = 'Seguidor'), (SELECT id FROM poderes WHERE nome = 'Proficiência')),
((SELECT id FROM origens WHERE nome = 'Seguidor'), (SELECT id FROM poderes WHERE nome = 'Surto Heroico')),
((SELECT id FROM origens WHERE nome = 'Selvagem'), (SELECT id FROM poderes WHERE nome = 'Lobo Solitário')),
((SELECT id FROM origens WHERE nome = 'Selvagem'), (SELECT id FROM poderes WHERE nome = 'Vida Rústica')),
((SELECT id FROM origens WHERE nome = 'Selvagem'), (SELECT id FROM poderes WHERE nome = 'Vitalidade')),
((SELECT id FROM origens WHERE nome = 'Soldado'), (SELECT id FROM poderes WHERE nome = 'Influência Militar')),
((SELECT id FROM origens WHERE nome = 'Taverneiro'), (SELECT id FROM poderes WHERE nome = 'Gororoba')),
((SELECT id FROM origens WHERE nome = 'Taverneiro'), (SELECT id FROM poderes WHERE nome = 'Proficiência')),
((SELECT id FROM origens WHERE nome = 'Taverneiro'), (SELECT id FROM poderes WHERE nome = 'Vitalidade')),
((SELECT id FROM origens WHERE nome = 'Trabalhador'), (SELECT id FROM poderes WHERE nome = 'Atlético')),
((SELECT id FROM origens WHERE nome = 'Trabalhador'), (SELECT id FROM poderes WHERE nome = 'Esforçado'));
